--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Tanmayboy/Minion-pogit-pm5
build-by-default: true
branches:
- main
projects:
  Minion-pogit-pm5:
    path: ""
requirements:
  - name: DevTools
    version: "1.17.1"
...
